version: "3"
    
networks:
  docker_deploy_education_network:
    driver: bridge
    
services:
  api:
    container_name: api
    image: sivuch999/docker-deploy:latest # เปลี่ยนเป็นชื่อ image บน hub ของตัวเอง
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - DB_NAME=education_db
    ports:
      - 8080:8080
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - docker_deploy_education_network

  mysql:
    # platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'education_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    healthcheck:
      test: mysql -uroot education_db -e 'select 1'
      interval: 2s
      timeout: 60s
      retries: 40
    networks:
      - docker_deploy_education_network