version: "3"
    
services:
  api:
    container_name: api
    image: sivuch999/docker-deploy:latest
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DB_HOST=35.240.148.166
      - DB_PORT=3306
      - DB_USERNAME=root
      - DB_PASSWORD=Tk~a-i4*N8n}aC5@
      - DB_NAME=education_db
    ports:
      - 8080:8080
    # depends_on:
    #   - mysql

    # mysql:
    #   platform: linux/x86_64
    #   image: mysql:5.7
    #   restart: always
    #   environment:
    #     MYSQL_DATABASE: 'deploy_test'
    #     MYSQL_USER: 'user'
    #     MYSQL_PASSWORD: 'password'
    #     MYSQL_ROOT_PASSWORD: 'Passw0rd'
    #   ports:
    #     - 3307:3306
    #   volumes:
    #     - ./mysql:/var/lib/mysql

volumes:
  mysql:
